"""Offline integration check for Phase 2 DES <-> demo_sim_core.

Instantiates the real SimulationCore (no WebSocket), steps it like the run
loop would, and verifies that genuine packet-level metrics emerge:
  - packets are generated, forwarded and delivered
  - aggregate throughput and per-link tx are non-zero
  - SUL/SSL uplinks carry traffic (UAVs/ships -> nearest ground station)
  - per-node counters and e2e latency are populated
"""
import time
from demo_sim_core import DemoSimCore


def main():
    core = DemoSimCore()
    core.is_playing = True
    core.speed = 1.0

    n_ticks = 150  # 150 * 0.2s = 30s of sim time
    t0 = time.time()
    last = None
    for _ in range(n_ticks):
        core.sim_time += core.update_interval * core.speed
        last = core.get_state_update()
    wall = time.time() - t0

    p = last["payload"]
    links = p["links"]
    nm = p["node_metrics"]
    ms = p["metrics_summary"]

    print("=" * 60)
    print(f"  sim_time={p['timestamp']}s  ticks={n_ticks}  wall={wall:.2f}s"
          f"  ({n_ticks / wall:.0f} ticks/s)")
    print("=" * 60)
    print(f"  links total       : {len(links)}")
    by_type = {}
    for lk in links.values():
        by_type.setdefault(lk["t"], []).append(lk)
    for lt, lst in sorted(by_type.items()):
        tx = sum(x["tx"] for x in lst)
        active = sum(1 for x in lst if x["tx"] > 0)
        print(f"    {lt:4s}: n={len(lst):3d}  carrying={active:3d}"
              f"  sum_tx={tx/1e6:8.2f} Mbps")

    print("-" * 60)
    print(f"  pkts_delivered    : {ms['pkts_delivered']}")
    print(f"  pkts_dropped      : {ms['pkts_dropped']}")
    print(f"  pkts_in_flight    : {ms['pkts_in_flight']}")
    print(f"  avg_e2e_latency_ms: {ms['avg_e2e_latency_ms']}")
    print(f"  aggregate_thrput  : {ms['aggregate_throughput_bps']/1e6:.2f} Mbps")
    print(f"  avg_utilization   : {ms['avg_utilization']}")

    # Per-node sample
    uavs = [k for k in nm if k.startswith("UAV-")]
    ships = [k for k in nm if k.startswith("Ship-")]
    sats = [k for k in nm if k.startswith("Sat-")]
    gs = [k for k in nm if not k.startswith(("UAV-", "Ship-", "Sat-"))]
    print("-" * 60)
    if uavs:
        u = nm[uavs[0]]
        print(f"  {uavs[0]:10s} sent={u['pkts_sent']} recv={u['pkts_recv']}"
              f" e2e={u['e2e_latency_ms']}ms jitter={u['jitter_ms']}ms")
    if ships:
        s = nm[ships[0]]
        print(f"  {ships[0]:10s} sent={s['pkts_sent']} recv={s['pkts_recv']}"
              f" e2e={s['e2e_latency_ms']}ms jitter={s['jitter_ms']}ms")
    if sats:
        fwd = sum(nm[k]["pkts_fwd"] for k in sats)
        print(f"  satellites  total fwd={fwd}")
    if gs:
        recv = sum(nm[k]["pkts_recv"] for k in gs)
        print(f"  ground stns total recv={recv}")

    # ---- Assertions ----
    errs = []
    if ms["pkts_delivered"] <= 0:
        errs.append("no packets delivered")
    if ms["aggregate_throughput_bps"] <= 0:
        errs.append("zero aggregate throughput")
    sul_tx = sum(x["tx"] for x in by_type.get("sul", []))
    ssl_tx = sum(x["tx"] for x in by_type.get("ssl", []))
    if sul_tx <= 0:
        errs.append("SUL uplinks carry no traffic")
    if ssl_tx <= 0:
        errs.append("SSL uplinks carry no traffic")
    if ms["avg_e2e_latency_ms"] <= 0:
        errs.append("zero e2e latency")
    sent = sum(nm[k]["pkts_sent"] for k in uavs + ships)
    if sent <= 0:
        errs.append("no packets generated by UAVs/ships")

    print("=" * 60)
    if errs:
        print("  FAIL:")
        for e in errs:
            print("   -", e)
        raise SystemExit(1)
    print("  PASS: real packet-level metrics are flowing end-to-end")
    print("=" * 60)


if __name__ == "__main__":
    main()
